apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cluster01-nginx
  name: cluster01-nginx-loadbalancer
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: cluster01-nginx
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cluster01-nginx
  name: cluster01-nginx-clusterip
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: cluster01-nginx

